language: node_js
sudo: required
node_js:
  - "6"
before_script:
  - npm install -g gulp typings
env:
  - PRODUCTION=TRUE
install:
  - npm install -g typings
  - typings install
  - npm install
script: gulp build