language: node_js
sudo: required
node_js:
  - "6"
env:
  - PRODUCTION=TRUE
install:
  - npm install -g typings gulp
before_script:
  - npm install
  - typings install
script: gulp build
after_success:
  - gulp deploy
notifications:
  slack: rungsikavarnich:gNm3pL1k70jxyDYZgjMpguIR
  email:
    - rungsikorn@me.com
    - aiirinversoul@gmail.com